export const ADDITIONAL_THEMES = `
  "neon-cyber": {
    label: "Neon Cyber",
    createdAt: "2026-03-11",
    styles: {
      light: {
        background: "#fdfcff",
        foreground: "#0d0221",
        card: "#ffffff",
        "card-foreground": "#0d0221",
        popover: "#ffffff",
        "popover-foreground": "#0d0221",
        primary: "#00e5ff",
        "primary-foreground": "#001015",
        secondary: "#f1ecff",
        "secondary-foreground": "#1a0a3e",
        muted: "#f4f3ff",
        "muted-foreground": "#6b6392",
        accent: "#ff2afc",
        "accent-foreground": "#ffffff",
        destructive: "#ff4b6e",
        "destructive-foreground": "#ffffff",
        border: "#e8e5ff",
        input: "#eceaff",
        ring: "#00e5ff",
        "chart-1": "#00e5ff",
        "chart-2": "#ff2afc",
        "chart-3": "#39ff14",
        "chart-4": "#ffe600",
        "chart-5": "#ff6a00",
        sidebar: "#f6f4ff",
        "sidebar-foreground": "#0d0221",
        "sidebar-primary": "#00e5ff",
        "sidebar-primary-foreground": "#001015",
        "sidebar-accent": "#eceaff",
        "sidebar-accent-foreground": "#1a0a3e",
        "sidebar-border": "#eceaff",
        "sidebar-ring": "#00e5ff",
        "font-sans": "Plus Jakarta Sans, sans-serif",
        "font-serif": "Lora, serif",
        "font-mono": "IBM Plex Mono, monospace",
        radius: "1.4rem",
        "shadow-color": "hsl(265 100% 30%)",
        "shadow-opacity": "0.2",
        "shadow-blur": "8px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "3px",
        "letter-spacing": "-0.025em",
        spacing: "0.27rem",
      },

      dark: {
        background: "#0d0221",
        foreground: "#e9e6ff",
        card: "#140533",
        "card-foreground": "#e9e6ff",
        popover: "#140533",
        "popover-foreground": "#e9e6ff",
        primary: "#00e5ff",
        "primary-foreground": "#001015",
        secondary: "#1a0a3e",
        "secondary-foreground": "#dcd6ff",
        muted: "#1a0a3e",
        "muted-foreground": "#7c6f9f",
        accent: "#ff2afc",
        "accent-foreground": "#ffffff",
        destructive: "#ff4b6e",
        "destructive-foreground": "#ffffff",
        border: "#2d1b69",
        input: "#2d1b69",
        ring: "#00e5ff",
        "chart-1": "#00e5ff",
        "chart-2": "#ff2afc",
        "chart-3": "#39ff14",
        "chart-4": "#ffe600",
        "chart-5": "#ff6a00",
        sidebar: "#090019",
        "sidebar-foreground": "#e9e6ff",
        "sidebar-primary": "#00e5ff",
        "sidebar-primary-foreground": "#001015",
        "sidebar-accent": "#1a0a3e",
        "sidebar-accent-foreground": "#00e5ff",
        "sidebar-border": "#2d1b69",
        "sidebar-ring": "#00e5ff",
        "font-sans": "Plus Jakarta Sans, sans-serif",
        "font-serif": "Lora, serif",
        "font-mono": "IBM Plex Mono, monospace",
        radius: "1.4rem",
        "shadow-color": "hsl(190 100% 50%)",
        "shadow-opacity": "0.35",
        "shadow-blur": "12px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "4px",
        "letter-spacing": "-0.025em",
        spacing: "0.27rem",
      },
    },
  },

  "cosmic-glass": {
    label: "Cosmic Glass",
    createdAt: "2026-09-02",
    styles: {
      light: {
        background: "#faf7fc",
        foreground: "#1c1024",
        card: "#ffffff",
        "card-foreground": "#1c1024",
        popover: "#ffffff",
        "popover-foreground": "#1c1024",
        primary: "#db2777",
        "primary-foreground": "#ffffff",
        secondary: "#f3e8ff",
        "secondary-foreground": "#581c87",
        muted: "#f7f2fb",
        "muted-foreground": "#6b5b7a",
        accent: "#fce7f3",
        "accent-foreground": "#9d174d",
        destructive: "#e11d48",
        "destructive-foreground": "#ffffff",
        border: "#eadff2",
        input: "#eadff2",
        ring: "#db2777",
        "chart-1": "#db2777",
        "chart-2": "#9333ea",
        "chart-3": "#7c3aed",
        "chart-4": "#c026d3",
        "chart-5": "#a21caf",
        sidebar: "#f7f2fb",
        "sidebar-foreground": "#1c1024",
        "sidebar-primary": "#db2777",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#fce7f3",
        "sidebar-accent-foreground": "#9d174d",
        "sidebar-border": "#eadff2",
        "sidebar-ring": "#db2777",
        "font-sans": "Plus Jakarta Sans, sans-serif",
        "font-serif": "Lora, serif",
        "font-mono": "IBM Plex Mono, monospace",
        radius: "0.85rem",
        "shadow-color": "hsl(320 80% 45%)",
        "shadow-opacity": "0.12",
        "shadow-blur": "16px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "6px",
        "letter-spacing": "-0.01em",
      },

      dark: {
        background: "#0a0a12",
        foreground: "#f5f3fb",
        card: "rgba(32, 22, 54, 0.45)",
        "card-foreground": "#f5f3fb",
        popover: "rgba(20, 14, 34, 0.9)",
        "popover-foreground": "#f5f3fb",
        primary: "#db2777",
        "primary-foreground": "#ffffff",
        secondary: "#2e1065",
        "secondary-foreground": "#e9d5ff",
        muted: "rgba(255, 255, 255, 0.06)",
        "muted-foreground": "#b9b3c9",
        accent: "#7c3aed",
        "accent-foreground": "#ffffff",
        destructive: "#f43f5e",
        "destructive-foreground": "#ffffff",
        border: "rgba(255, 255, 255, 0.12)",
        input: "rgba(255, 255, 255, 0.16)",
        ring: "#ec4899",
        "chart-1": "#f472b6",
        "chart-2": "#c084fc",
        "chart-3": "#a78bfa",
        "chart-4": "#f9a8d4",
        "chart-5": "#d8b4fe",
        sidebar: "rgba(20, 14, 34, 0.6)",
        "sidebar-foreground": "#f5f3fb",
        "sidebar-primary": "#db2777",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#7c3aed",
        "sidebar-accent-foreground": "#ffffff",
        "sidebar-border": "rgba(255, 255, 255, 0.12)",
        "sidebar-ring": "#ec4899",
        "font-sans": "Plus Jakarta Sans, sans-serif",
        "font-serif": "Lora, serif",
        "font-mono": "IBM Plex Mono, monospace",
        radius: "0.85rem",
        "shadow-color": "hsl(320 90% 50%)",
        "shadow-opacity": "0.3",
        "shadow-blur": "24px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "8px",
        "letter-spacing": "-0.01em",
      },
    },
  },
`;
