export const ADDITIONAL_THEMES = `
  "neon-cyber": {
    label: "Neon Cyber",
    createdAt: "2026-03-11",
    styles: {
      light: {
        background: "#fdfcff",
        foreground: "#0d0221",
        card: "#ffffff",
        "card-foreground": "#0d0221",
        popover: "#ffffff",
        "popover-foreground": "#0d0221",
        primary: "#00e5ff",
        "primary-foreground": "#001015",
        secondary: "#f1ecff",
        "secondary-foreground": "#1a0a3e",
        muted: "#f4f3ff",
        "muted-foreground": "#6b6392",
        accent: "#ff2afc",
        "accent-foreground": "#ffffff",
        destructive: "#ff4b6e",
        "destructive-foreground": "#ffffff",
        border: "#e8e5ff",
        input: "#eceaff",
        ring: "#00e5ff",
        "chart-1": "#00e5ff",
        "chart-2": "#ff2afc",
        "chart-3": "#39ff14",
        "chart-4": "#ffe600",
        "chart-5": "#ff6a00",
        sidebar: "#f6f4ff",
        "sidebar-foreground": "#0d0221",
        "sidebar-primary": "#00e5ff",
        "sidebar-primary-foreground": "#001015",
        "sidebar-accent": "#eceaff",
        "sidebar-accent-foreground": "#1a0a3e",
        "sidebar-border": "#eceaff",
        "sidebar-ring": "#00e5ff",
        "font-sans": "Plus Jakarta Sans, sans-serif",
        "font-serif": "Lora, serif",
        "font-mono": "IBM Plex Mono, monospace",
        radius: "1.4rem",
        "shadow-color": "hsl(265 100% 30%)",
        "shadow-opacity": "0.2",
        "shadow-blur": "8px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "3px",
        "letter-spacing": "-0.025em",
        spacing: "0.27rem",
      },

      dark: {
        background: "#0d0221",
        foreground: "#e9e6ff",
        card: "#140533",
        "card-foreground": "#e9e6ff",
        popover: "#140533",
        "popover-foreground": "#e9e6ff",
        primary: "#00e5ff",
        "primary-foreground": "#001015",
        secondary: "#1a0a3e",
        "secondary-foreground": "#dcd6ff",
        muted: "#1a0a3e",
        "muted-foreground": "#7c6f9f",
        accent: "#ff2afc",
        "accent-foreground": "#ffffff",
        destructive: "#ff4b6e",
        "destructive-foreground": "#ffffff",
        border: "#2d1b69",
        input: "#2d1b69",
        ring: "#00e5ff",
        "chart-1": "#00e5ff",
        "chart-2": "#ff2afc",
        "chart-3": "#39ff14",
        "chart-4": "#ffe600",
        "chart-5": "#ff6a00",
        sidebar: "#090019",
        "sidebar-foreground": "#e9e6ff",
        "sidebar-primary": "#00e5ff",
        "sidebar-primary-foreground": "#001015",
        "sidebar-accent": "#1a0a3e",
        "sidebar-accent-foreground": "#00e5ff",
        "sidebar-border": "#2d1b69",
        "sidebar-ring": "#00e5ff",
        "font-sans": "Plus Jakarta Sans, sans-serif",
        "font-serif": "Lora, serif",
        "font-mono": "IBM Plex Mono, monospace",
        radius: "1.4rem",
        "shadow-color": "hsl(190 100% 50%)",
        "shadow-opacity": "0.35",
        "shadow-blur": "12px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "4px",
        "letter-spacing": "-0.025em",
        spacing: "0.27rem",
      },
    },
  },

  "cosmic-glass": {
    label: "Cosmic Glass",
    createdAt: "2026-09-02",
    // Round 2 (maintainer feedback): the navbar glass treatment was liked,
    // but (a) every other translucent surface (cards, filters sheet,
    // dialogs/popovers, footer) needs the same glass treatment, not just the
    // navbar - see the [data-theme-id=cosmic-glass] rules in
    // app/globals.css this preset drives, plus the decorative background
    // gradient there that gives the blur something to blur - and (b) no pink
    // anywhere: every color that was pink/magenta/fuchsia (primary, accent,
    // ring, chart-1..5, sidebar-accent) moved to a purple/violet-only
    // palette. destructive intentionally stays red/rose - that is the
    // shared semantic danger token every theme preset uses, not part of
    // this theme's decorative accent palette.
    styles: {
      light: {
        background: "#f7f5fc",
        foreground: "#1e1533",
        card: "rgba(255, 255, 255, 0.55)",
        "card-foreground": "#1e1533",
        popover: "rgba(255, 255, 255, 0.75)",
        "popover-foreground": "#1e1533",
        primary: "#7c3aed",
        "primary-foreground": "#ffffff",
        secondary: "#ede9fe",
        "secondary-foreground": "#4c1d95",
        muted: "rgba(124, 58, 237, 0.06)",
        "muted-foreground": "#655a78",
        accent: "#ede9fe",
        "accent-foreground": "#5b21b6",
        destructive: "#e11d48",
        "destructive-foreground": "#ffffff",
        border: "rgba(124, 58, 237, 0.16)",
        input: "rgba(124, 58, 237, 0.18)",
        ring: "#7c3aed",
        // Chosen (and contrast-checked, see the doc comment above) so each
        // of the 5 chart colors independently clears 4.5:1 as topic-chip
        // text against this theme's own ~16%-tinted chip background - the
        // lighter violet-500/-400 shades in the earlier revision read fine
        // as solid swatches but dropped under 4.5:1 once used as text on a
        // low-opacity tint of themselves.
        "chart-1": "#6d28d9",
        "chart-2": "#7e22ce",
        "chart-3": "#4f46e5",
        "chart-4": "#5b21b6",
        "chart-5": "#6b21a8",
        sidebar: "rgba(255, 255, 255, 0.6)",
        "sidebar-foreground": "#1e1533",
        "sidebar-primary": "#7c3aed",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#ede9fe",
        "sidebar-accent-foreground": "#5b21b6",
        "sidebar-border": "rgba(124, 58, 237, 0.16)",
        "sidebar-ring": "#7c3aed",
        "font-sans": "Plus Jakarta Sans, sans-serif",
        "font-serif": "Lora, serif",
        "font-mono": "IBM Plex Mono, monospace",
        radius: "0.85rem",
        "shadow-color": "hsl(263 70% 45%)",
        "shadow-opacity": "0.12",
        "shadow-blur": "16px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "6px",
        "letter-spacing": "-0.01em",
      },

      dark: {
        background: "#0a0a12",
        foreground: "#f3f1fb",
        card: "rgba(32, 22, 54, 0.45)",
        "card-foreground": "#f3f1fb",
        popover: "rgba(20, 14, 34, 0.9)",
        "popover-foreground": "#f3f1fb",
        // #8b5cf6 (violet-500) against white foreground text only cleared
        // 4.23:1 - just under AA's 4.5:1 for normal-size button text - so
        // primary/ring/sidebar-primary/sidebar-ring use the darker #7c3aed
        // here too (5.7:1), matching the light palette instead of a
        // separate dark-mode shade.
        primary: "#7c3aed",
        "primary-foreground": "#ffffff",
        secondary: "#2e1065",
        "secondary-foreground": "#e9d5ff",
        muted: "rgba(255, 255, 255, 0.06)",
        "muted-foreground": "#b9b3c9",
        accent: "#7c3aed",
        "accent-foreground": "#ffffff",
        destructive: "#f43f5e",
        "destructive-foreground": "#ffffff",
        border: "rgba(255, 255, 255, 0.12)",
        input: "rgba(255, 255, 255, 0.16)",
        ring: "#7c3aed",
        "chart-1": "#a78bfa",
        "chart-2": "#c084fc",
        "chart-3": "#a5b4fc",
        "chart-4": "#ddd6fe",
        "chart-5": "#c4b5fd",
        sidebar: "rgba(20, 14, 34, 0.6)",
        "sidebar-foreground": "#f3f1fb",
        "sidebar-primary": "#7c3aed",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#7c3aed",
        "sidebar-accent-foreground": "#ffffff",
        "sidebar-border": "rgba(255, 255, 255, 0.12)",
        "sidebar-ring": "#7c3aed",
        "font-sans": "Plus Jakarta Sans, sans-serif",
        "font-serif": "Lora, serif",
        "font-mono": "IBM Plex Mono, monospace",
        radius: "0.85rem",
        "shadow-color": "hsl(263 80% 55%)",
        "shadow-opacity": "0.3",
        "shadow-blur": "24px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "8px",
        "letter-spacing": "-0.01em",
      },
    },
  },
`;
